### ISSUE TITLE
Implement NLP Analyzer & Anonymizer

### ISSUE THREAD

**Issue by michaeltheedev** [NCATComp410/comp410_fall_2022#165]
Implementing pattern recognition for phone number PII

**Comment by claesmk** [comment]
The default analyzer seems to detect most US phone numbers. It will not detect something like 000-000-0000 but it will detect something like 919-555-1212

**Comment by claesmk** [comment]
As you work on sprint-4 you will need to decide if there is any custom work needed for phone numbers or if the default implementation in the analyzer works OK for you. If you are happy with the default implementation you can close this issue.
