### ISSUE TITLE
PII - Add support for Mastercard

### ISSUE THREAD

**Issue by imsimmons** [NCATComp410/comp410_fall_2022#172]

**Comment by claesmk** [comment]
It's possible that the default analyzer will detect Mastercard OK, however, I had trouble getting it to recognize a number such as 1234-1234-1234-1234 which, is not really a valid card number.  It may be necessary to use a number with a valid prefix such as in the [example](https://github.com/NCATComp410/comp410_fall_2022/blob/49dcb65ae61c18d3f26d839721628863123ef858/test_pii_detect.py#L78)
