### ISSUE TITLE
PII - Add support for AMEX

### ISSUE THREAD

**Issue by ahjoyner** [NCATComp410/comp410_fall_2022#173]

**Comment by claesmk** [comment]
This looks good.  The default analyzer seems to detect visa/mastercard numbers but does not detect amex.  In sprint-4 you will need to modify my [example](https://github.com/NCATComp410/comp410_fall_2022/blob/49dcb65ae61c18d3f26d839721628863123ef858/pii_detect.py#L35) to detect amex.
