### ISSUE TITLE
Frost: Add support for US SSN

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_fall_2022#60]
Finds all occurrences of a US Social Security Number in a text string

**Comment by DougGajda** [comment]
![Error 1](https://user-images.githubusercontent.com/112100715/196487685-8f50471d-d1e8-49aa-8e37-384db5c7c551.PNG)
Hello Mr. Claes, I was able to create a regex to start off as a base to the solution, but every time I try running the debugger I keep getting this error message. On the Pii file there are no errors as shown below in next comment. How do I go about this, and what am I supposed to put in the assertEqual spot. I saw that your comment said to add assertion here. Thanks

**Comment by DougGajda** [comment]
![No Error 1](https://user-images.githubusercontent.com/112100715/196488425-c918be7f-ae69-4ca0-8776-ead08d056d4d.PNG)
